
server:
  port: 8411

# logging
logging:
  level:
    org:
      springframework:
        web: debug
        security: debug
      hibernate:
        type:
          descriptor:
            sql: trace
    com:
      htmlcomponent: debug

spring:
  application:
    name: htmlcomponent
  datasource:
    url: jdbc:mysql://localhost:3306/editor?serverTimezone=Asia/Seoul
    username: editor
    password: editor!@#
    initialization-mode: always
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: create
  main:
    allow-bean-definition-overriding: true